### PR TITLE
Add M7E Hecto Support

### PR DESCRIPTION
**Pull request by sfe-SparkFro**
M7E has some minor differences that required updates to get it working, mainly just different region and extra bytes to read memory banks.

Also modified all the examples to have user-selectable serial interface, baud rate, and module type. This removed the need for the dedicated hardware serial examples.

All changes are backwards compatible with original library.

### CODE REVIEW

**Review by gigapod — COMMENTED** [review]
Looks good:
 - nits on examples - really from the previous version
 - Note on a control statement block

**Comment by SFE-Brudnerd** [comment]
Was asked to review. Looks good to me!

**Comment by lewispg228** [comment]
Nice improvements and good clear additional commenting (thanks!). Your update to readData()... wow, way to sleuth that one with the logic analyzer. It all looks good to me!

**Review by gigapod — COMMENTED** [review]
Looks good

**Pull request merged**
